name: Exécution des tests avec pytest

on: [push]  # Exécuter les tests à chaque poussée

jobs:
  tests:
    runs-on: ubuntu-latest  # Utiliser une machine virtuelle Ubuntu
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
    
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Exécution des tests
      run: |
        pytest
