name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest

      - name: Run unittest
        run: python -m unittest discover

      - name: Run pytest with coverage
        run: pytest --cov=calculatrice test_pytest_calculatrice.py

      - name: Run unittest with coverage
        run: coverage run --source=calculatrice test_unittest.py

      - name: Run Security bandit test
        run : bandit calculatrice.py

      - name: Run Behave Acceptation tests
        run: behave